### ISSUE TITLE
Januári beadandó

### ISSUE THREAD

**Issue by csuzli57** [Teaching-projects/januari-beadando-csuzli57#1]
Jó napot tanár úr!
leadtam a projekt feladatot Sölét_Gergely_januári_beadandó néven

**Comment by hegyhati** [comment]
Jopofa, negyes megvan, otosert par dolgot pimpelj meg rajta:

- az elejen a `ct`-t es a `t`-t bevezeted, az nem azt csinalja, amire gondolsz. Probald meg, hogy beirod neki, hogy terrorista futaskor.
- a dict-ek indentalasa nem szep
- jelenleg ha jol ertem, egy fegyvert vasarolunk csak. ha ez volt a  cel, ok, ha nem, akkor nem jol mukodik.
- a t/ct reszt jo volna fuggvenybe kiszervezni.

**Comment by csuzli57** [comment]
Jó napot Tanár úr!
Meg probáltam kijavítani az összeset és az én kódom célja hogy egy fegyvert tudjunk venni.

**Comment by hegyhati** [comment]
ok, 5.
